-- Insertion generated by chatGPT 4o to populate the database manually instead of reading, parsing and filtering the JSON file.

INSERT INTO categories (name) VALUES ('html');
INSERT INTO categories (name) VALUES ('css');
INSERT INTO categories (name) VALUES ('javascript');
-- Question 1
INSERT INTO questions (category_id, question_text) VALUES (1, 'Ef við værum að smíða vefsíðu og myndum vilja geta farið frá index.html yfir á about.html, hvað væri best að nota?') RETURNING id;

-- Assume question_id = 101
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(1, '<a href="about.html">About</a>', true),
(1, '<form method="get" action="about.html"><button>About</button></form>', false),
(1, '<button to="about.html">About</button>', false),
(1, 'Allar jafn góðar / All equally good', false);

-- Question 2
INSERT INTO questions (category_id, question_text) VALUES (1, 'Í <head> á vefjum setjum við <meta charset="utf-8"> (eða það stafasett sem nota á), afhverju er það gert?') RETURNING id;

-- Assume question_id = 102
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(2, 'Þannig að stafir birtist rétt.', true),
(2, 'Skilgreining sem visual studio verður að hafa þannig að prettier virki rétt.', false),
(2, 'Skilgreining sem aXe krefur okkur um til að vefur verði aðgengilegur.', false),
(2, 'Ekkert af þessu.', false);

-- Question 3
INSERT INTO questions (category_id, question_text) VALUES (1, 'Það sem við getum gert til að forrita aðgengilega vefi er') RETURNING id;

-- Assume question_id = 103
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(3, ' Allt af þessu.', true),
(3, 'Nota eingöngu lyklaborð við að skoða og nota vefinn.', false),
(3, 'Merkja form á aðgengilegan hátt.', false),
(3, 'Hafa tóman alt texta á myndum ef þær eru eingöngu til skrauts.', false);

-- Question 4
INSERT INTO questions (category_id, question_text) VALUES (1, 'Hvað er merkingarfræði í sambandi við námsefnið?') RETURNING id;

-- Assume question_id = 104
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(4, 'Hvert HTML element hefur einhverja skilgreinda merkingu—merkingarfræðilegt gildi—sem við þurfum að hafa í huga þegar við smíðum vefi.', true),
(4, 'Hvert HTML tag hefur einhverja skilgreinda merkingu—merkingarfræðilegt gildi—sem við þurfum að hafa í huga þegar við smíðum vefi.', false),
(4, 'Hvert CSS eigindi hefur einhverja skilgreinda merkingu—merkingarfræðilegt gildi—sem við þurfum að hafa í huga þegar við smíðum vefi.', false),
(4, 'Hver CSS selector hefur einhverja skilgreinda merkingu—merkingarfræðilegt gildi—sem við þurfum að hafa í huga þegar við smíðum vefi.', false);

-- Insert questions and answers for CSS

-- Question 1
INSERT INTO questions (category_id, question_text) VALUES (2, 'Fyrir eftirfarandi HTML / for the following HTML:\n\n<div class="text">\n  <h1 class="important text__title">Halló heimur</h1>\n</div>\n\nEr skilgreint CSS / there is defined CSS:\n\n.text {\n  font-size: 10px;\n  color: green;\n}\n\n.text .text__title {\n  font-size: 1.5em;\n}\n\n.important {\n  font-size: 2em;\n  color: red;\n}\n\nHvert af eftirfarandi er satt fyrir textann „Halló heimur“ eftir að búið er að reikna gildi?') RETURNING id;

-- Insert answers for question 1
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(5, 'font-size: 20px;, color: green;', true),
(5, 'font-size: 15px;, color: red;', false),
(5, 'font-size: 20px;, color: red;', false),
(5, 'font-size: 15px;, color: green;', false);

-- Question 2
INSERT INTO questions (category_id, question_text) VALUES (2, 'Ef við erum að nota nýtt gildi fyrir lit í CSS sem er ekki víst að sé stutt í öllum vöfrum, þá ættum við að') RETURNING id;

-- Insert answers for question 2
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(6, 'Skilgreina fallback gildi á undan nýja gildinu sem væri notað í stað þess ef það er ekki stutt', true),
(6, 'Skilgreina fallback gildi á eftir nýja gildinu sem væri notað í stað þess ef það er ekki stutt.', false),
(6, 'Setja upp JavaScript virkni sem bendir notanda á að sækja nýjann vafra sem styður gildið.', false),
(6, 'Þetta er ekki stutt í CSS.', false);

-- Question 3
INSERT INTO questions (category_id, question_text) VALUES (2, 'Í verkefnum höfum við unnið með „containers“ og „items“ sem hugtök, hvað á það við?') RETURNING id;

-- Insert answers for question 3
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(7, '„Flex container“ og „flex items; „grid container“ og „grid items“: greinarmunur á foreldri og börnum þegar flexbox og CSS grid er notað.', true),
(7, '„Flex container“ og „flex items: greinarmunur á foreldri og börnum eingngu þegar flexbox er notað.', false),
(7, '„Grid container“ og „grid items“: greinarmunur á foreldri og börnum eingöngu þegar grid er notað.', false),
(7, 'Hugtök sem eru notuð með `querySelectorAll`: „container“ er það element sem leitað er undir, „items“ það sem er skilað.', false);

-- Question 4
INSERT INTO questions (category_id, question_text) VALUES (2, 'Þegar við notum flexbox hvað af eftirfarandi er satt? Gerið ráð fyrir að skjal sé lesið frá vinstri til hægri.') RETURNING id;

-- Insert answers for question 4
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(8, 'Höfum skilgreinda tvo ása: aðalás og krossás sem eru hornréttir; sjálfgefin röðun er á aðalás frá vinstri til hægri.', true),
(8, 'Höfum skilgreinda tvo ása: aðalás og krossás sem eru samsíða; sjálfgefin röðun er á aðalás frá vinstri til hægri.', false),
(8, 'Höfum skilgreinda tvo ása: aðalás og krossás sem eru hornréttir; sjálfgefin röðun er á krossás frá vinstri til hægri.', false),
(8, 'Höfum skilgreinda tvo ása: aðalás og krossás sem eru samsíða; sjálfgefin röðun er á krossás frá vinstri til hægri.', false);

-- Insert questions and answers for JavaScript

-- Question 1
INSERT INTO questions (category_id, question_text) VALUES (3, 'Hvað er skrifað út eftir að eftirfarandi kóði er keyrður?\n\nconst items = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\n\nconst іtem = items\n  .map((i) => i * 2)\n  .filter((i) => i < 10)\n  .find((i) => i > 6)\n\nconsole.log(item);') RETURNING id;

-- Insert answers for question 1
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(9, '8', true),
(9, '[8]', false),
(9, 'Uncaught ReferenceError: item is not defined', false),
(9, 'undefined', false);

-- Question 2
INSERT INTO questions (category_id, question_text) VALUES (3, 'Þegar við berum saman gildi í JavaScript ættum við alltaf að nota þrjú samasem merki (`===`) því að') RETURNING id;

-- Insert answers for question 2
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(10, 'Þessi samanburður byrjar á að bera saman týpur gilda og kemst því framhjá type coercion sem gerist með samanburð með tveimur samasem merkjum.', true),
(10, 'Við ættum alltaf að nota tvö samasem merki, ekki þrjú því þá byrjum við á að bera saman týpur gilda og komumst þannig framhjá type coercion.', false),
(10, 'Þessi samanburður kemst framhjá truthy og falsy gildum og skilar eingöngu réttum niðurstöðum fyrir primitive gildi.', false),
(10, 'Þessi samanburður nýtir lógíska virkja sem virka aðeins í tvístæðum.', false);

-- Question 3
INSERT INTO questions (category_id, question_text) VALUES (3, 'Þegar við notum `fetch` í JavaScript ætti ferlið við að sækja gögn að vera') RETURNING id;

-- Insert answers for question 3
INSERT INTO answers (question_id, answer_text, is_correct) VALUES 
(11, 'Búið til `fetch` request kall sem tilgreinir að minnsta kosti URL; villuathugun á kalli og svari með tilliti til HTTP; gögn sótt í response með villuathugun.', true),
(11, 'Búið til `fetch` request kall sem verður að tilgreina URL, HTTP aðferð og stöðukóða; villuathugun á kalli og svari með tilliti til HTTP; gögn sótt í response með villuathugun.', false),
(11, 'Búið til `fetch` request kall sem tilgreinir að minnsta kosti URL; villuathugun á kalli og svari með tilliti til URL; gögn sótt í response.', false),
(11, 'Búið til `fetch` request kall sem tilgreinir að minnsta kosti URL; villuathugun á kalli og svari með tilliti til HTTP; eingöngu JSON gögn sótt í response með villuathugun.', false);
